package com.rdc.auth.controller;

import com.rdc.auth.dto.*;
import com.rdc.auth.entity.User;
import com.rdc.auth.repository.UserRepository;
import com.rdc.auth.service.UserService;
import com.rdc.auth.util.JwtUtil;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.net.URI;
import java.util.Map;


@RestController
@RequestMapping("/auth")
@RequiredArgsConstructor
@Slf4j
public class AuthController {

    private final UserService userService;
    private final UserRepository userRepository;
    private final JwtUtil jwtUtil;

    @Value("${frontend.url}")
    private String frontendUrl;

    private static final String EMAIL_SPAM_ALERT =
            "Check your Spam folder and mark the email as 'Not Spam'.";

    @PostMapping("/signup")
    public ResponseEntity<?> signup(@RequestBody LoginRequest req) {
        try {
            return ResponseEntity.ok(userService.createUser(req.getEmail(), req.getPassword()));
        } catch (Exception e) {
            return ResponseEntity.badRequest().body(Map.of("error", e.getMessage()));
        }
    }

    @PostMapping("/login")
    public ResponseEntity<?> login(@RequestBody LoginRequest req) {
        return processLogin(req.getEmail(), req.getPassword(), "USER");
    }

    @PostMapping("/admin/login")
    public ResponseEntity<?> adminLogin(@RequestBody LoginRequest req) {
        // Enforce role separation at the service layer [cite: 269]
        return processLogin(req.getEmail(), req.getPassword(), "ADMIN");
    }

    @PostMapping("/password/request-reset")
    public ResponseEntity<?> requestReset(@RequestBody Map<String, String> req) {
        String email = req.get("email");
        try {
            if (email != null && !email.isBlank()) {
                userService.createPasswordResetToken(email);
            }
        } catch (Exception e) {
            log.warn("Reset email failed for {}: {}", email, e.getMessage());
        }
        return ResponseEntity.ok(Map.of(
                "message", "If an account exists, a reset link has been sent.",
                "alert", EMAIL_SPAM_ALERT
        ));
    }

    @PostMapping("/password/reset")
    public ResponseEntity<?> resetPassword(@RequestBody Map<String, String> req) {
        try {
            userService.resetPassword(req.get("token"), req.get("newPassword"));
            return ResponseEntity.ok(Map.of("message", "Password updated successfully."));
        } catch (Exception e) {
            return ResponseEntity.badRequest().body(Map.of("error", e.getMessage()));
        }
    }

    @GetMapping("/verify-email")
    public ResponseEntity<Void> verifyEmail(@RequestParam("token") String token) {
        String redirectUrl;
        try {
            userService.verifyAccount(token);
            redirectUrl = frontendUrl + "/verification-success";
        } catch (Exception e) {
            redirectUrl = frontendUrl + "/verification-failed?error=" + e.getMessage().replace(" ", "_");
        }
        return ResponseEntity.status(HttpStatus.FOUND).location(URI.create(redirectUrl)).build();
    }

    /**
     * Internal Authentication Logic
     * ENSURES: JWT subject is ALWAYS the numeric ID for both Users and Admins.
     */
    private ResponseEntity<?> processLogin(String email, String password, String role) {
        try {
            // Service layer validates credentials and role [cite: 208, 269]
            String accessToken = userService.authenticate(email, password, role);
            User user = userRepository.findByEmail(email).orElseThrow();

            // accessToken generated by JwtUtil uses String.valueOf(user.getId())
            return ResponseEntity.ok(new TokenResponse(
                    accessToken,
                    jwtUtil.generateRefreshToken(user),
                    jwtUtil.getAccessTokenExpirationSeconds()
            ));
        } catch (Exception e) {
            log.error("Login failed for role {}: {}", role, e.getMessage());
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED)
                    .body(Map.of("error", "INVALID_CREDENTIALS"));
        }
    }
}