package com.rdc.auth.service;

import com.rdc.auth.entity.User;
import com.rdc.auth.entity.VerificationToken;
import com.rdc.auth.repository.UserRepository;
import com.rdc.auth.repository.VerificationTokenRepository;
import com.rdc.auth.util.JwtUtil;
import com.rdc.auth.exception.UserAlreadyExistsException;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import jakarta.transaction.Transactional;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

@Service
@Slf4j
public class UserServiceImpl implements UserService {

    private final UserRepository userRepository;
    private final VerificationTokenRepository verificationTokenRepository;
    private final PasswordEncoder passwordEncoder;
    private final SmtpEmailService emailService;
    private final JwtUtil jwtUtil;

    @Value("${frontend.url:http://localhost:5173}")
    private String frontendUrl;

    private final Map<String, Instant> resendRateLimits = new ConcurrentHashMap<>();
    private final Map<String, Integer> resendCounts = new ConcurrentHashMap<>();

    private static final int RESEND_COOLDOWN_MINUTES = 2;
    private static final int MAX_RESENDS_PER_HOUR = 3;

    public UserServiceImpl(
            UserRepository userRepository,
            VerificationTokenRepository verificationTokenRepository,
            PasswordEncoder passwordEncoder,
            SmtpEmailService emailService,
            JwtUtil jwtUtil
    ) {
        this.userRepository = userRepository;
        this.verificationTokenRepository = verificationTokenRepository;
        this.passwordEncoder = passwordEncoder;
        this.emailService = emailService;
        this.jwtUtil = jwtUtil;
    }

    @Override
    @Transactional
    public User createUser(String email, String password) {
        log.info("Creating new user: {}", email); // Fixed log
        if (userRepository.findByEmail(email).isPresent()) {
            throw new UserAlreadyExistsException("User with this email already exists.");
        }

        // Line 63 Fix: Uses Lombok Builder
        User newUser = User.builder()
                .email(email)
                .passwordHash(passwordEncoder.encode(password))
                .role("USER")
                .createdAt(Instant.now())
                .isVerified(false)
                .enabled(true)
                .build();

        newUser = userRepository.save(newUser);
        sendVerificationToken(newUser);
        log.info("User created successfully: {}", email); // Fixed log
        return newUser;
    }

    private void sendVerificationToken(User user) {
        String token = UUID.randomUUID().toString();
        Instant expiryDate = Instant.now().plusSeconds(24 * 3600);

        verificationTokenRepository.save(new VerificationToken(token, user, expiryDate));
        String verificationLink = "http://localhost:8081/auth/verify-email?token=" + token;

        // Line 88 Fix: Using user.getEmail()
        emailService.sendVerificationEmail(user.getEmail(), verificationLink);
    }

    @Override
    @Transactional
    public void verifyAccount(String token) {
        VerificationToken vt = verificationTokenRepository.findByToken(token)
                .orElseThrow(() -> new IllegalArgumentException("Verification token is invalid."));

        // Line 196 Fix: getExpiryDate() from Lombok @Data
        if (vt.getExpiryDate().isBefore(Instant.now())) {
            verificationTokenRepository.delete(vt);
            throw new IllegalArgumentException("Verification token has expired.");
        }

        // Line 200/201 Fix: getUser() and setVerified()
        User user = vt.getUser();
        user.setVerified(true); // Matches helper or Lombok isVerified setter
        userRepository.save(user);
        verificationTokenRepository.delete(vt);
    }

    @Override
    @Transactional
    public void createPasswordResetToken(String email) {
        userRepository.findByEmail(email).ifPresent(user -> {
            String token = UUID.randomUUID().toString();
            // Line 135/136 Fix: setters generated by @Data
            user.setResetToken(token);
            user.setResetTokenExpiryDate(Instant.now().plusSeconds(600));
            userRepository.save(user);

            String resetLink = frontendUrl + "/reset-password?token=" + token;
            emailService.sendPasswordResetEmail(email, resetLink);
        });
    }

    @Override
    @Transactional
    public void resetPassword(String token, String newPassword) {
        User user = userRepository.findByResetToken(token)
                .orElseThrow(() -> new IllegalArgumentException("Invalid or expired reset token."));

        // Line 150 Fix: getResetTokenExpiryDate()
        if (user.getResetTokenExpiryDate() != null && user.getResetTokenExpiryDate().isBefore(Instant.now())) {
            throw new IllegalArgumentException("Reset token has expired.");
        }

        // Line 154 Fix: setPasswordHash()
        user.setPasswordHash(passwordEncoder.encode(newPassword));
        user.setResetToken(null);
        user.setResetTokenExpiryDate(null);
        userRepository.save(user);
    }

    // Rate limit check
    private void checkResendRateLimit(String email) {
        Instant lastResend = resendRateLimits.get(email);
        Integer count = resendCounts.getOrDefault(email, 0);

        if (lastResend != null) {
            Instant cooldownEnd = lastResend.plus(RESEND_COOLDOWN_MINUTES, ChronoUnit.MINUTES);
            if (Instant.now().isBefore(cooldownEnd)) {
                long secondsRemaining = ChronoUnit.SECONDS.between(Instant.now(), cooldownEnd);
                throw new IllegalStateException(String.format("Wait %d seconds.", secondsRemaining));
            }
        }
        if (count >= MAX_RESENDS_PER_HOUR) {
            throw new IllegalStateException("Hourly limit reached.");
        }
    }

    @Override
    @Transactional
    public void resendVerificationEmail(String email) {
        User user = userRepository.findByEmail(email)
                .orElseThrow(() -> new IllegalArgumentException("User not found."));
        if (user.isVerified()) { // Line 99 Fix
            throw new IllegalArgumentException("Already verified.");
        }
        checkResendRateLimit(email);
        verificationTokenRepository.deleteByUser(user);
        sendVerificationToken(user);
        resendRateLimits.put(email, Instant.now());
        resendCounts.put(email, resendCounts.getOrDefault(email, 0) + 1);
    }

    @Override
    public String authenticateAndGetJwt(String email, String password) {
        User user = userRepository.findByEmail(email)
                .orElseThrow(() -> new IllegalArgumentException("Invalid credentials."));
        if (!passwordEncoder.matches(password, user.getPasswordHash())) {
            throw new IllegalArgumentException("Invalid credentials.");
        }
        if (!user.isVerified()) {
            throw new IllegalStateException("Email not verified");
        }
        return jwtUtil.generateToken(user);
    }

    @Override
    @Transactional
    public String authenticateOrCreateGoogleUser(String email, String name, String pictureUrl) {
        User user = userRepository.findByEmail(email).orElseGet(() -> {
            User newUser = User.builder()
                    .email(email)
                    .passwordHash(UUID.randomUUID().toString())
                    .displayName(name)
                    .role("USER")
                    .createdAt(Instant.now())
                    .isVerified(true)
                    .enabled(true)
                    .build();
            return userRepository.save(newUser);
        });
        if (!user.isVerified()) {
            user.setVerified(true);
            userRepository.save(user);
        }
        return jwtUtil.generateToken(user);
    }
}