version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin

      MYSQL_DATABASE: asset_db
    # ports:
    #   - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rdc-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build: ./auth-service
    container_name: auth-service
    env_file:
      - ./env/auth-service.env
    environment:
      DB_URL: jdbc:mysql://mysql:3306/auth_db?useSSL=false&allowPublicKeyRetrieval=true
      SERVICE_SUBSCRIPTION_URL: http://subscription-service:8094
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - rdc-network

  admin-service:
    build: ./admin-service
    container_name: admin-service
    env_file:
      - ./env/admin-service.env
    environment:
      DB_URL: jdbc:mysql://mysql:3306/admin_db?useSSL=false&allowPublicKeyRetrieval=true
      ASSET_SERVICE_URL: http://asset-service:8090
      ORDER_SERVICE_URL: http://order-service:8095
      CART_SERVICE_URL: http://cart-service:8091
      WISHLIST_SERVICE_URL: http://wishlist-service:8093
      PAYMENT_SERVICE_URL: http://payment-service:8092
      SUBSCRIPTION_SERVICE_URL: http://subscription-service:8094
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - rdc-network

  asset-service:
    build: ./asset-service
    container_name: asset-service
    env_file:
      - ./env/asset-service.env
    environment:
      DB_URL: jdbc:mysql://mysql:3306/asset_db?useSSL=false&allowPublicKeyRetrieval=true
      ORDER_SERVICE_URL: http://order-service:8095
      ADMIN_SERVICE_URL: http://admin-service:8080
    ports:
      - "8090:8090"
    volumes:
      - ./data/uploads:/app/data/uploads
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - rdc-network

  cart-service:
    build: ./cart-service
    container_name: cart-service
    env_file:
      - ./env/cart-service.env
    environment:
      DB_URL: jdbc:mysql://mysql:3306/cart_db?useSSL=false&allowPublicKeyRetrieval=true
      ADMIN_SERVICE_URL: http://admin-service:8080
    ports:
      - "8091:8091"
    depends_on:
      mysql:
        condition: service_healthy
      admin-service:
        condition: service_started
      auth-service:
        condition: service_started
    networks:
      - rdc-network

  order-service:
    build: ./order-service
    container_name: order-service
    env_file:
      - ./env/order-service.env
    environment:
      DB_URL: jdbc:mysql://mysql:3306/order_db
      SERVICE_CART_URL: http://cart-service:8091
      SERVICE_WISHLIST_URL: http://wishlist-service:8093
      SERVICE_AUTH_URL: http://auth-service:8081
      SERVICE_ADMIN_URL: http://admin-service:8080
      SERVICE_PAYMENT_URL: http://payment-service:8092
      SERVICE_SUBSCRIPTION_URL: http://subscription-service:8094
      SERVICE_ASSET_URL: http://asset-service:8090
    ports:
      - "8095:8095"
    depends_on:
      mysql:
        condition: service_healthy
      cart-service:
        condition: service_started
      auth-service:
        condition: service_started
      admin-service:
        condition: service_started
    networks:
      - rdc-network

  payment-service:
    build: ./payment-service
    container_name: payment-service
    env_file:
      - ./env/payment-service.env
    environment:
      DB_URL: jdbc:mysql://mysql:3306/payment_db
      ORDER_SERVICE_URL: http://order-service:8095
      SUBSCRIPTION_SERVICE_URL: http://subscription-service:8094
    ports:
      - "8092:8092"
    depends_on:
      mysql:
        condition: service_healthy
      order-service:
        condition: service_started
    networks:
      - rdc-network

  subscription-service:
    build: ./subscription-service
    container_name: subscription-service
    env_file:
      - ./env/subscription-service.env
    environment:
      DB_URL: jdbc:mysql://mysql:3306/subscription_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      AUTH_SERVICE_URL: http://auth-service:8081
      ORDER_SERVICE_URL: http://order-service:8095
      PAYMENT_SERVICE_URL: http://payment-service:8092
      ADMIN_SERVICE_URL: http://admin-service:8080
    ports:
      - "8094:8094"
    depends_on:
      mysql:
        condition: service_healthy
      auth-service:
        condition: service_started
      admin-service:
        condition: service_started
      order-service:
        condition: service_started
      payment-service:
        condition: service_started
    networks:
      - rdc-network

  wishlist-service:
    build: ./wishlist-service
    container_name: wishlist-service
    env_file:
      - ./env/wishlist-service.env
    environment:
      DB_URL: jdbc:mysql://mysql:3306/wishlist_db?useSSL=false&allowPublicKeyRetrieval=true
      DESIGN_SERVICE_URL: http://admin-service:8080
      ORDER_SERVICE_URL: http://order-service:8095
    ports:
      - "8093:8093"
    depends_on:
      mysql:
        condition: service_healthy
      admin-service:
        condition: service_started
      auth-service:
        condition: service_started
    networks:
      - rdc-network

volumes:
  mysql_data:

networks:
  rdc-network:
    driver: bridge
