CREATE TABLE verification_token (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    CONSTRAINT FK_VERIFICATION_USER FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);