spring.application.name=payment-service

server.port=8092

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/payment_db?useSSL=false
spring.datasource.username=root
spring.datasource.password=admin

# Razorpay Credentials (Get from Razorpay Dashboard)
razorpay.api.key=rzp_test_S0wq0wupm
razorpay.api.secret=Eq7EZsY21p3wYhD7Rp
#razorpay.webhook.secret=

# Microservice URLs
service.order.url=http://localhost:8095

# JWT Secret - MUST MATCH AUTH SERVICE EXACTLY
jwt.secret=GiyIPHik/GoBi0wEARevwq9A1x/nNqzzg8v2xICuxFU=