ALTER TABLE payments ADD COLUMN plan_id BIGINT NULL;
ALTER TABLE payments ADD COLUMN purchase_type VARCHAR(30) NOT NULL DEFAULT 'ORDER';
ALTER TABLE payments MODIFY COLUMN order_id BIGINT NULL;

ALTER TABLE payments MODIFY COLUMN order_id BIGINT NULL;