spring.application.name=admin-service

server.port=8080

# Spring Data Source Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/admin_db?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin

# Spring JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway (optional)
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration

# expose actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics,env
management.endpoint.health.shw-details=always


service.asset.url=http://localhost:8090


# application.properties
spring.web.cors.allow-credentials=true
spring.web.cors.allowed-origin-patterns=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.max-age=3600

server.error.include-stacktrace=never