spring.application.name=order-service
server.port=8095

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# Security Settings
jwt.secret=${JWT_SECRET}
internal.service.key=${INTERNAL_SERVICE_KEY}

# Internal Bridge URLs
service.cart.url=${SERVICE_CART_URL}
service.auth.url=${SERVICE_AUTH_URL}
service.admin.url=${SERVICE_ADMIN_URL}
service.payment.url=${SERVICE_PAYMENT_URL}
service.asset.url=${SERVICE_ASSET_URL}

# CORS Configuration
spring.web.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

# Email Configuration
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_SMTP_STARTTLS}
rdc.accounts.email=${ACCOUNTS_EMAIL}
# Storage Configuration
app.storage.location=${STORAGE_PATH}