server.port=8095
spring.application.name=order-service

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/order_db?useSSL=false
spring.datasource.username=root
spring.datasource.password=admin

# JWT Secret - MUST MATCH AUTH & PAYMENT
jwt.secret=GiyIPHik/GoBi0wEARevwq9A1x/nNqzzg8v2xICuxFU=

# Flyway
spring.flyway.enabled=true

# Add this to both Order and Payment service environments
internal.service.key=ORDER_PAYMENT_BRIDGE_KEY
