spring.application.name=asset-service
server.port=8090

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/asset_db?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin

# JPA & Flyway
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.repair-on-migrate=true

# Multipart Settings for Uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# FIX: JWT Secret (Must match Order/Payment Service exactly)
jwt.secret=GiyIPHik/GoBi0wEARevwq9A1x/nNqzzg8v2xICuxFU=

# FIX: Microservice URLs (Points to Order Service)
service.order.url=http://localhost:8095

# FIX: Shared Internal Key (For the verify-download bridge)
internal.service.key=ORDER_PAYMENT_BRIDGE_KEY

# Absolute path for windows (Use forward slashes)
app.storage.location=C:/Users/admin8/Desktop/RDC/Back-end/data/uploads
