spring.application.name=asset-service
server.port=8090

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ? RECOMMENDED for initial fix
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=true

# Max file size allowed
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

jwt.secret=${JWT_SECRET}
internal.service.key=${INTERNAL_SERVICE_KEY}

service.order.url=${ORDER_SERVICE_URL}
service.admin.url=${ADMIN_SERVICE_URL}

spring.web.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
app.storage.location=${STORAGE_PATH}